#!/bin/bash

cp inst-script/mac/scm.yml.mac $INSTALL_DIR/config/scm.yml

if [ ! -f /opt/local/apache2/Authn/Redmine.pm ]
then
  mkdir -p /opt/local/apache2/Authn
  cp config/Redmine.pm /opt/local/apache2/Authn/
fi

if [ ! -f /opt/local/apache2/conf/redmine.conf ]
then
  mkdir -p /opt/local/apache2/conf
  PASSENGER_VERSION=`passenger-config --version`

  sed 's/%HOSTNAME%/'$HOSTNAME'/' inst-script/mac/httpd-redmine.conf | \
      sed 's/%PASSENGER_VERSION%/'$PASSENGER_VERSION'/' |
    if [ "$SSL" = "y" ]
    then
        sed 's/#Rewrite/Rewrite/'
    else
        cat
    fi > /opt/local/apache2/conf/redmine.conf

  sed 's/%HOSTNAME%/'$HOSTNAME'/' inst-script/mac/httpd-vcs.conf >  /opt/local/apache2/conf/vcs.conf

  if [ "$SSL" = "y" ]
  then
      CHK=`grep "^DocumentRoot /opt/alminium/public" /opt/local/apache2/conf/ssl.conf`
      if [ "$CHK" = "" ]
      then
          sed 's/#DocumentRoot "\/var\/www\/html"/DocumentRoot \/opt\/alminium\/public/' /opt/local/apache2/conf/extra/httpd-ssl.conf > /tmp/ssl.conf
          cp /tmp/ssl.conf /opt/local/apache2/conf/ssl.conf
      fi
  fi
fi

pushd .

cd /opt/local/apache2/libexec
/opt/local/apache2/bin/apxs -a -e -n "perl" mod_perl.so

popd

launchctl load -w /Library/LaunchDaemons/org.macports.apache2.plist
/opt/local/apache2/bin/apachectl restart
