#!/bin/bash
echo "*******************************************************"
echo "  セキュリティの設定"
echo "*******************************************************"
echo "ファイアフォールの設定はシステム環境設定から行ってください。"
echo "共有で、Web共有がHTTPSとSSLに、リモートログインがSSHに対応しています。"
echo \n

port install `grep -v "^#" inst-script/mac/packages.lst`

if [ "$SSL" = "y" ]
then
   port install openssl
fi

sudo -u mysql mysql_install_db5

cp /opt/local/share/mysql5/mysql/my-small.cnf /opt/local/etc/mysql5/my.cnf
launchctl load -w /Library/LaunchDaemons/org.macports.mysql5.plist
