#!/bin/bash

mysql alminium -e "drop database alminium" 
rm -fr /opt/alminium /var/opt/alminium
rm -fr /etc/apache2/sites-available/vcs
rm -fr /etc/apache2/sites-available/redmine
rm -fr /etc/apache2/sites-enabled/vcs
rm -fr /etc/apache2/sites-enabled/redmine
rm -fr /etc/httpd/conf.d/redmine.conf
rm -fr /etc/httpd/conf.d/vcs.conf
