#!/bin/bash

GEM=`which gem1.9.3`

if [ "$GEM" = "" ]
then
  GEM=gem
fi
  

echo "ALMiniumをアンインストールします。"
echo ""
echo -n "データベース(全てのRedmineの情報)とリポジトリを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    mysql alminium -e "drop database alminium" 
    rm -fr /opt/alminium /var/opt/alminium
fi

echo ""
echo -n "Apacheの設定を削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    rm -fr /etc/apache2/sites-available/vcs
    rm -fr /etc/apache2/sites-available/redmine
    rm -fr /etc/apache2/sites-enabled/vcs
    rm -fr /etc/apache2/sites-enabled/redmine
    rm -fr /etc/httpd/conf.d/redmine.conf
    rm -fr /etc/httpd/conf.d/vcs.conf
    rm -fr /etc/httpd/conf.d/jenkins.conf
fi

echo ""
echo -n "Passengerを削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    echo "3" | $GEM uninstall passenger
fi

echo ""
echo -n "キャッシュされたファイルを削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    rm -fr cache *.installed
fi
