#!/bin/bash
# rubygems.lstからgemのリストを取得しインストール

GEM=`which gem1.9`

if [ "$GEM" = "" ]
then
  GEM=gem
fi

# インストールするディレクトリ名
NAME=(`grep -v "^#" config/rubygems.lst | awk -F, '{print $1}'`)
VER=(`grep -v "^#" config/rubygems.lst | awk -F, '{print $2}'`)

for (( i = 0; i < ${#NAME[@]}; ++i ))
do
  NAME=${NAME[$i]}
  VER=${VER[$i]}
  if [ "$VER" = "-" ]
  then
    $GEM install $NAME --no-rdoc --no-ri
  else
    $GEM install $NAME -v=$VER --no-rdoc --no-ri
  fi
done


## install mod_passenger
case $OS in
    rhel6)
        if [ ! -f /usr/lib64/ruby/gems/1.9.1/gems/passenger-3.*/ext/apache2/mod_passenger.so ]
        then
            $GEM install passenger --no-rdoc --no-ri
            passenger-install-apache2-module --auto
        fi
        ;;
    mac)
        if [ ! -f /opt/local/lib/ruby1.9/gems/1.9.1/gems/passenger-3.*/ext/apache2/mod_passenger.so ]
        then
            $GEM install passenger --no-rdoc --no-ri
            export APXS2=/opt/local/apache2/bin/apxs
            export PATH=/opt/local/apache2/bin:$PATH
            passenger-install-apache2-module --auto
        fi
        ;;
    debian)
        if [ ! -f /var/lib/gems/1.9.1/gems/passenger-3.0.*/ext/apache2/mod_passenger.so ]
        then
            $GEM install thin
            $GEM install passenger --no-rdoc --no-ri
            passenger-install-apache2-module --auto
        fi
        ;;

esac
