#!/bin/bash
# rubygems.lstからgemのリストを取得しインストール

# インストールするディレクトリ名
NAME=(`grep -v "^#" config/rubygems.lst | awk -F, '{print $1}'`)
VER=(`grep -v "^#" config/rubygems.lst | awk -F, '{print $2}'`)

for (( i = 0; i < ${#NAME[@]}; ++i ))
do
  NAME=${NAME[$i]}
  VER=${VER[$i]} 
  case $OS in
  rhel6)
    if [ "$VER" = "-" ]
    then
      gem install $NAME --no-rdoc --no-ri
    else 
      gem install $NAME -v=$VER --no-rdoc --no-ri
    fi
    ;;
  mac)
    if [ "$VER" = "-" ]
    then
      sudo gem install $NAME --no-rdoc --no-ri
    else 
      sudo gem install $NAME -v=$VER --no-rdoc --no-ri
    fi
    ;;
  esac
done


## install mod_passenger
case $OS in
    rhel6) 
        if [ ! -f /usr/lib/ruby/gems/1.8/gems/passenger-3.*/ext/apache2/mod_passenger.so ]
        then
            gem install passenger --no-rdoc --no-ri
            passenger-install-apache2-module --auto
        fi
        ;;
    mac)
	if [ ! -f /Library/Ruby/Gems/1.8/gems/passenger-3.*/ext/apache2/mod_passenger.so ]
        then
            sudo gem install passenger --no-rdoc --no-ri
            sudo passenger-install-apache2-module --auto
        fi
        ;;
esac

pushd .

cd cache
if [ ! -f redcarpet ]
then
  git clone https://github.com/alminium/redcarpet.git
  cd redcarpet 

 if [ "$OS" = "rhel6" ]
  then
      rake install 
  else
      gem install rake -v=0.8.7 --no-rdoc --no-ri
      gem install rake-compiler --no-rdoc --no-ri
      /var/lib/gems/1.8/gems/rake-0.8.7/bin/rake install
  fi
fi

popd
