#!/bin/bash
echo "*******************************************************"
echo "  セキュリティの設定"
echo "*******************************************************"
echo "アプリケーションを動作させるために、ファイアフォールの設定とSELinuxの無効化を行います。"
echo "nと答えると手動でセキュリティの設定が必要となります。分らない場合はYと答えてください。"
echo 
echo -n "アプリケーションを動作させるためにセキュリティの設定を行いますか?[Y/n]"
read USE_DISABLE_SECURITY
if [ -f /etc/yum.repos.d/epel.repo ]
then
  CHK=`grep "enabled=1" /etc/yum.repos.d/epel.repo`
  if [ "$CHK" = "" ]
  then
    sed '1,/enabled=0/s/enabled=0/enabled=1/' /etc/yum.repos.d/epel.repo >/tmp/epel.repo
    mv -f /tmp/epel.repo /etc/yum.repos.d/epel.repo
  fi
else
  rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-6.noarch.rpm
fi
yum -y --nogpgcheck install `grep -v "^#" inst-script/rhel6/packages.lst`

if [ "$SSL" = "y" ]
then
    yum -y install mod_ssl
fi

chkconfig --add mysqld
chkconfig mysqld on
service mysqld start

if [[ `which ruby` == "" || ! `ruby --version` =~ 1.9.3 ]]
then
    bash inst-script/rhel6/ruby1.9-install
fi
